import { EXPENSE_CATEGORIES, FUEL_TYPES, PAYMENT_METHODS, ROLE_OPTIONS, STATUS_OPTIONS } from "@/lib/constants";
import { formatCurrency, formatDate, formatNumber, formatRawNumber } from "@/utils/format";

const dateField = { type: "date" };

export const moduleConfigs = {
  pumps: {
    title: "Pump Management",
    description: "Create and manage each petrol pump separately.",
    endpoint: "pumps",
    searchFields: ["name", "code", "address"],
    filters: [
      { name: "status", label: "Status", type: "select", options: ["", "Active", "Inactive"] },
    ],
    fields: [
      { name: "name", label: "Pump Name", type: "text" },
      { name: "code", label: "Pump Code", type: "text" },
      { name: "address", label: "Address", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      { key: "name", label: "Pump Name" },
      { key: "code", label: "Code" },
      { key: "status", label: "Status" },
      { key: "address", label: "Address" },
    ],
  },
  "fuel-purchases": {
    title: "Fuel Purchase Management",
    description: "Record supplier deliveries and update tank stock automatically.",
    endpoint: "fuel-purchases",
    searchFields: ["supplierName", "invoiceNumber", "fuelType"],
    filters: [
      { name: "fuelType", label: "Fuel Type", type: "select", options: ["", ...FUEL_TYPES] },
    ],
    fields: [
      { name: "fuelType", label: "Fuel Type", type: "select", options: FUEL_TYPES },
      { name: "quantityLiters", label: "Quantity (Liters)", type: "number" },
      { name: "pricePerLiter", label: "Price Per Liter", type: "number" },
      { name: "supplierName", label: "Supplier Name", type: "text" },
      { name: "invoiceNumber", label: "Invoice Number", type: "text" },
      { name: "date", label: "Date", ...dateField },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      { key: "date", label: "Date", formatter: formatDate },
      { key: "fuelType", label: "Fuel Type" },
      { key: "quantityLiters", label: "Liters", formatter: formatRawNumber },
      { key: "pricePerLiter", label: "Rate", formatter: formatCurrency },
      { key: "totalAmount", label: "Total", formatter: formatCurrency },
      { key: "supplierName", label: "Supplier" },
      { key: "invoiceNumber", label: "Invoice" },
    ],
  },
  "fuel-sales": {
    title: "Shift Sales Management",
    description: "Enter manual meter readings and calculate sold liters automatically.",
    endpoint: "fuel-sales",
    searchFields: ["shiftName", "operatorName", "nozzleName", "customer", "fuelType"],
    filters: [
      { name: "fuelType", label: "Fuel Type", type: "select", options: ["", ...FUEL_TYPES] },
      { name: "paymentType", label: "Payment Type", type: "select", options: ["", "Cash", "Credit"] },
    ],
    fields: [
      { name: "shiftName", label: "Shift Name", type: "text" },
      { name: "operatorName", label: "Operator Name", type: "text" },
      { name: "nozzleName", label: "Nozzle Name", type: "text" },
      { name: "fuelType", label: "Fuel Type", type: "select", options: FUEL_TYPES },
      { name: "openingMeterReading", label: "Opening Meter Reading", type: "number" },
      { name: "closingMeterReading", label: "Closing Meter Reading", type: "number" },
      { name: "fuelPricePerLiter", label: "Fuel Price Per Liter", type: "number" },
      { name: "paymentType", label: "Payment Type", type: "select", options: ["Cash", "Credit"] },
      { name: "customer", label: "Customer Name", type: "text" },
      { name: "amountReceived", label: "Amount Received", type: "number" },
      { name: "pendingAmount", label: "Pending Amount", type: "number" },
      { name: "date", label: "Date", ...dateField },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      { key: "date", label: "Date", formatter: formatDate },
      { key: "shiftName", label: "Shift" },
      { key: "operatorName", label: "Operator" },
      { key: "nozzleName", label: "Nozzle" },
      { key: "fuelType", label: "Fuel" },
      { key: "soldLiters", label: "Sold Liters", formatter: formatRawNumber },
      { key: "totalSaleAmount", label: "Sale Amount", formatter: formatCurrency },
      { key: "paymentType", label: "Payment" },
    ],
  },
  tanks: {
    title: "Tank Stock Management",
    description: "Track current stock, tank capacity, and low stock alerts.",
    endpoint: "tanks",
    searchFields: ["fuelType", "notes"],
    filters: [
      { name: "fuelType", label: "Fuel Type", type: "select", options: ["", ...FUEL_TYPES] },
    ],
    fields: [
      { name: "fuelType", label: "Fuel Type", type: "select", options: FUEL_TYPES },
      { name: "currentStock", label: "Current Stock", type: "number" },
      { name: "capacityLiters", label: "Capacity Liters", type: "number" },
      { name: "lowStockThreshold", label: "Low Stock Threshold", type: "number" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      { key: "fuelType", label: "Fuel Type" },
      { key: "currentStock", label: "Current Stock", formatter: formatRawNumber },
      { key: "capacityLiters", label: "Capacity", formatter: formatRawNumber },
      { key: "lowStockThreshold", label: "Low Threshold", formatter: formatRawNumber },
      { key: "updatedAt", label: "Updated", formatter: formatDate },
    ],
  },
  nozzles: {
    title: "Nozzle / Dispenser Management",
    description: "Keep nozzle machines, fuel type, and meter readings up to date.",
    endpoint: "nozzles",
    searchFields: ["nozzleName", "machineName", "fuelType"],
    filters: [
      { name: "fuelType", label: "Fuel Type", type: "select", options: ["", ...FUEL_TYPES] },
      { name: "status", label: "Status", type: "select", options: ["", ...STATUS_OPTIONS] },
    ],
    fields: [
      { name: "nozzleName", label: "Nozzle Name", type: "text" },
      { name: "machineName", label: "Machine Name", type: "text" },
      { name: "fuelType", label: "Fuel Type", type: "select", options: FUEL_TYPES },
      { name: "currentMeterReading", label: "Current Meter Reading", type: "number" },
      { name: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
    columns: [
      { key: "nozzleName", label: "Nozzle" },
      { key: "machineName", label: "Machine" },
      { key: "fuelType", label: "Fuel Type" },
      { key: "currentMeterReading", label: "Meter", formatter: formatRawNumber },
      { key: "status", label: "Status" },
    ],
  },
  shifts: {
    title: "Shift Operations",
    description: "Track operator shifts, openings, closings, and shift status.",
    endpoint: "shifts",
    searchFields: ["shiftName", "operatorName", "status"],
    filters: [
      { name: "status", label: "Status", type: "select", options: ["", "Open", "Closed", "Pending"] },
    ],
    fields: [
      { name: "shiftName", label: "Shift Name", type: "text" },
      { name: "operatorName", label: "Operator Name", type: "text" },
      { name: "startTime", label: "Start Time", ...dateField },
      { name: "endTime", label: "End Time", type: "date" },
      { name: "status", label: "Status", type: "select", options: ["Open", "Closed", "Pending"] },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      { key: "shiftName", label: "Shift" },
      { key: "operatorName", label: "Operator" },
      { key: "startTime", label: "Start", formatter: formatDate },
      { key: "endTime", label: "End", formatter: formatDate },
      { key: "status", label: "Status" },
    ],
  },
  expenses: {
    title: "Expense Management",
    description: "Capture daily operational expenses and categories.",
    endpoint: "expenses",
    searchFields: ["expenseTitle", "category", "description"],
    filters: [
      { name: "category", label: "Category", type: "select", options: ["", ...EXPENSE_CATEGORIES] },
    ],
    fields: [
      { name: "expenseTitle", label: "Expense Title", type: "text" },
      { name: "category", label: "Category", type: "select", options: EXPENSE_CATEGORIES },
      { name: "amount", label: "Amount", type: "number" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "date", label: "Date", ...dateField },
    ],
    columns: [
      { key: "date", label: "Date", formatter: formatDate },
      { key: "expenseTitle", label: "Title" },
      { key: "category", label: "Category" },
      { key: "amount", label: "Amount", formatter: formatCurrency },
    ],
  },
  customers: {
    title: "Credit Customer Management",
    description: "Manage customers purchasing fuel on credit and their outstanding balance.",
    endpoint: "customers",
    searchFields: ["name", "phone", "vehicleNumber", "companyName"],
    filters: [],
    fields: [
      { name: "name", label: "Customer Name", type: "text" },
      { name: "phone", label: "Phone", type: "text" },
      { name: "address", label: "Address", type: "textarea" },
      { name: "vehicleNumber", label: "Vehicle Number", type: "text" },
      { name: "companyName", label: "Company Name", type: "text" },
      { name: "pendingBalance", label: "Pending Balance", type: "number" },
    ],
    columns: [
      { key: "name", label: "Customer" },
      { key: "phone", label: "Phone" },
      { key: "vehicleNumber", label: "Vehicle" },
      { key: "companyName", label: "Company" },
      { key: "pendingBalance", label: "Pending", formatter: formatCurrency },
    ],
  },
  payments: {
    title: "Credit Recovery Payments",
    description: "Record received payments against customer credit balances.",
    endpoint: "payments",
    searchFields: ["customer", "note", "method"],
    filters: [
      { name: "method", label: "Method", type: "select", options: ["", ...PAYMENT_METHODS] },
    ],
    fields: [
      { name: "customer", label: "Customer Name or ID", type: "text" },
      { name: "amount", label: "Amount", type: "number" },
      { name: "method", label: "Method", type: "select", options: PAYMENT_METHODS },
      { name: "note", label: "Note", type: "textarea" },
      { name: "date", label: "Date", ...dateField },
    ],
    columns: [
      { key: "date", label: "Date", formatter: formatDate },
      { key: "customerName", label: "Customer" },
      { key: "amount", label: "Amount", formatter: formatCurrency },
      { key: "method", label: "Method" },
    ],
  },
  employees: {
    title: "Employee Management",
    description: "Manage employee profiles, attendance, salary, and shift assignments.",
    endpoint: "employees",
    searchFields: ["name", "cnic", "phone", "role", "shift"],
    filters: [
      { name: "role", label: "Role", type: "select", options: ["", "Admin", "Manager", "Operator"] },
      { name: "status", label: "Status", type: "select", options: ["", ...STATUS_OPTIONS] },
    ],
    fields: [
      { name: "name", label: "Name", type: "text" },
      { name: "cnic", label: "CNIC", type: "text" },
      { name: "phone", label: "Phone", type: "text" },
      { name: "role", label: "Role", type: "select", options: ROLE_OPTIONS },
      { name: "salary", label: "Salary", type: "number" },
      { name: "shift", label: "Shift", type: "text" },
      { name: "joiningDate", label: "Joining Date", ...dateField },
      { name: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
    columns: [
      { key: "name", label: "Employee" },
      { key: "role", label: "Role" },
      { key: "salary", label: "Salary", formatter: formatCurrency },
      { key: "shift", label: "Shift" },
      { key: "status", label: "Status" },
    ],
  },
  "stock-adjustments": {
    title: "Stock Adjustment",
    description: "Make manual fuel stock corrections with a clear reason and audit trail.",
    endpoint: "stock-adjustments",
    searchFields: ["fuelType", "reason"],
    filters: [
      { name: "fuelType", label: "Fuel Type", type: "select", options: ["", ...FUEL_TYPES] },
    ],
    fields: [
      { name: "fuelType", label: "Fuel Type", type: "select", options: FUEL_TYPES },
      { name: "adjustmentQuantity", label: "Adjustment Quantity", type: "number" },
      { name: "reason", label: "Reason", type: "textarea" },
      { name: "date", label: "Date", ...dateField },
    ],
    columns: [
      { key: "date", label: "Date", formatter: formatDate },
      { key: "fuelType", label: "Fuel Type" },
      { key: "adjustmentQuantity", label: "Adjustment", formatter: formatRawNumber },
      { key: "reason", label: "Reason" },
    ],
  },
  users: {
    title: "User Settings",
    description: "Create or manage application users and access roles.",
    endpoint: "users",
    searchFields: ["name", "email", "role", "status"],
    filters: [
      { name: "role", label: "Role", type: "select", options: ["", ...ROLE_OPTIONS] },
      { name: "status", label: "Status", type: "select", options: ["", ...STATUS_OPTIONS] },
    ],
    fields: [
      { name: "name", label: "Name", type: "text" },
      { name: "email", label: "Email", type: "email" },
      { name: "password", label: "Password", type: "password" },
      { name: "pumpId", label: "Pump", type: "select", optionsSource: "pumps" },
      { name: "role", label: "Role", type: "select", options: ROLE_OPTIONS },
      { name: "status", label: "Status", type: "select", options: STATUS_OPTIONS },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "pumpId", label: "Pump" },
      { key: "role", label: "Role" },
      { key: "status", label: "Status" },
    ],
  },
};

export function getModuleConfig(resource) {
  return moduleConfigs[resource];
}